---
# tasks file for ./roles/course_management

  - name: remove node modules
    shell: cd {{ app_home }} && echo "osg@1234" sudo -S rm -rf node_modules

  - name: install node modules
    shell: cd {{ app_home }} && echo "osg@1234" sudo -S /usr/local/bin/npm install --save

  - name: Run unit testcases
    shell: cd {{ app_home }} && echo "osg@1234" sudo -S /usr/local/bin/npm test

  - name: create build for production
    shell: cd {{ app_home }} && echo "osg@1234" sudo -S /usr/local/bin/npm run lintAndbuild

  # - name: install serve module
  #   become: yes
  #   shell: cd {{ app_home }} && echo "osg@1234" sudo -S /usr/local/bin/npm install serve --save