---
# tasks file for ./roles/course_management

  - name: install node modules
    shell: cd {{ app_home }} && npm install --save

  - name: create build for production
    shell: cd {{ app_home }} && npm run build --production

  - name: install serve module
    become: yes
    shell: cd {{ app_home }} && npm install -g serve